### ISSUE TITLE
Missing default output

### ISSUE THREAD

**Issue by adaliszk** [jdcrecur/swagger-chunk#1]
It would be nice if this package behaves just like swagger-cli or any other linux cli program by printing out the result to the stdout if we don't specify the destination. Currently, it throws an unformatted error, which is not a nice experience.

**Comment by jdcrecur** [comment]
If I get time, otherwise I would gladly accept a pull request :)

**Comment by adaliszk** [comment]
Eventually sure, currently I've solved my issue with the official `swagger-cli`. Surprisingly it does the same and lints at the same time 😉

**Comment by jdcrecur** [comment]
Official? Hardly. There are tools we built into this repo at our agency that are not present in the other options used on a few projects. Their use of swagger-parser is a nice addition though, I think I will add this.

**Comment by adaliszk** [comment]
Ah true, sorry. Anyway, I just run `swagger-cli bundle --dereference --outfile bundled.yaml src/swagger.yaml` and it packs a pretty modular yaml documentation with complex anchor structure alongside validating the structure.

**Comment by jdcrecur** [comment]
Jolly good Adam
