### ISSUE TITLE
Update documentation to use bin instead directly point to node_modules

### ISSUE THREAD

**Issue by adaliszk** [jdcrecur/swagger-chunk#3]
I wish to use `swagger-chunk` as a command instead of pointing to the folder and depending on npm's package resolution to find the main file. This looks more-less complete but the documentation is confusing about this. Please upgrade the documentation to use the package and don't make assumptions about my workspace by implying that I even have a node_modules folder (I could very well have a yarn workspace with a different folder).

**Comment by jdcrecur** [comment]
I don't really like globally install npm packages, they typically get out of date very quickly.

you can use the package name directly in the scripts though
