### ISSUE TITLE
YAML anchors breaking the workflow

### ISSUE THREAD

**Issue by adaliszk** [jdcrecur/swagger-chunk#6]
I cannot use YAML in its full potential because when I try to use anchors, chunk breaks on the first one without any error. Since this looks like working in another (swagger-cli) package which does the same, I assume this bundler does not runs yaml. It would be nice if we can run yaml functionalities and more, it would be nice to target when to run them, before or after dereferencing the $ref

**Comment by jdcrecur** [comment]
realted to your other issue raised
